-- KernelNews esquema (Neon Postgres / Vercel)
-- Pásalo en el editor SQL de Neon o con `psql`.

create table if not exists noticias (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  subtopic text default '',
  minutes int,
  date text,
  excerpt text,
  content text,
  image text,
  featured boolean default false,
  created_at timestamptz default now()
);

create table if not exists temas (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon text default '',
  orden int default 0,
  subtopics jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists eventos (
  id bigint generated by default as identity primary key,
  title text not null,
  date text,
  time text,
  location text,
  type text,
  description text,
  image text,
  posts jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);
